# Generated by Django 2.2.7 on 2019-12-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_for', models.CharField(choices=[('misbehave', 'Misbehave'), ('illegal gratification', 'Illegal Gratification'), ('faulty investigation', 'Faulty Investigation'), ('manhandling', 'Manhandling'), ('non registration of cases', 'Non registration of cases'), ('traffic', 'Traffic'), ('other', 'Other')], help_text='Misbehave', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('cnic', models.CharField(help_text='without dashes', max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], default='Trans', max_length=6)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(help_text='without dash', max_length=11)),
                ('email', models.EmailField(help_text='someone@example.com', max_length=254)),
                ('city', models.CharField(help_text='Islamabad', max_length=25)),
                ('against', models.CharField(choices=[('public', 'Public'), ('police', 'Police')], default='Public', max_length=10)),
                ('body', models.TextField(help_text='Please limit your text to 1800 characters only', max_length=1800)),
                ('adressed_to', models.CharField(choices=[('IGP', 'IGP'), ('DIG OPS', 'DIG OPS'), ('other', 'OTHER')], max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
    ]
