# Generated by Django 2.2.7 on 2019-12-05 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20191205_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='updated',
        ),
        migrations.AddField(
            model_name='complaint',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
