# Generated by Django 2.2.7 on 2019-12-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20191205_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(default='Islamabad', max_length=25),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_for',
            field=models.CharField(choices=[('misbehave', 'Misbehave'), ('illegal gratification', 'Illegal Gratification'), ('faulty investigation', 'Faulty Investigation'), ('manhandling', 'Manhandling'), ('non registration of cases', 'Non registration of cases'), ('traffic', 'Traffic'), ('other', 'Other')], default='Misbehave', max_length=20),
        ),
    ]
