# Generated by Django 2.2.7 on 2019-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20191205_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(choices=[('islamabad', 'Islamabad'), ('lahore', 'Lahore'), ('peshawar', 'Peshawar'), ('karachi', 'Karachi')], default='Islamabad', max_length=25),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cnic',
            field=models.CharField(help_text='without dashes', max_length=13, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(help_text='Full Name', max_length=50),
        ),
    ]
