# Generated by Django 2.2.7 on 2019-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20191205_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(choices=[('islamabad', 'Islamabad'), ('lahore', 'Lahore'), ('peshawar', 'Peshawar'), ('karachi', 'Karachi'), ('other', 'Other')], default='Islamabad', max_length=2),
        ),
    ]
