# Generated by Django 2.2.7 on 2019-12-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20191205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(choices=[('islamabad', 'Islamabad'), ('lahore', 'Lahore'), ('peshawar', 'Peshawar'), ('karachi', 'Karachi'), ('other', 'Other')], default='Islamabad', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('entertained', 'Entertained')], default='open', max_length=10),
        ),
    ]
