# Generated by Django 2.2.7 on 2019-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20191205_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('entertained', 'Entertained')], default='pending', max_length=10),
        ),
    ]
