# Generated by Django 2.2.7 on 2019-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20191205_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='publish',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('entertained', 'Entertained')], default='pending', max_length=11),
        ),
    ]
