# Generated by Django 2.2.7 on 2019-12-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20191206_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='body',
            new_name='complaint_details',
        ),
    ]
