# Generated by Django 2.2.7 on 2019-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_auto_20191214_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cnic',
            field=models.CharField(max_length=13, unique=True, verbose_name='CNIC'),
        ),
    ]
